<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\Users\yniak\Documents\PJ\PORTEFOLIO\protefolio-3d\static\models\git.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cylinder003: THREE.Mesh
      Cylinder004: THREE.Mesh
    }
    materials: {
      ['Material.008']: THREE.MeshStandardMaterial
      ['Material.009']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/git.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cylinder003.geometry}
      material={gltf.materials['Material.008']}
      position={[17.12, 9.06, -11.3]}
      scale={[2.53, 0.75, 2.53]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder004.geometry}
      material={gltf.materials['Material.009']}
      position={[17.12, 8.85, -11.3]}
      scale={[2.53, 1.06, 2.53]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
