<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\Users\yniak\Documents\PJ\PORTEFOLIO\protefolio-3d\static\models\linkedin.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube: THREE.Mesh
      Cube001: THREE.Mesh
      Cube002: THREE.Mesh
      Cylinder: THREE.Mesh
    }
    materials: {
      ['Material.001']: THREE.MeshStandardMaterial
      ['Material.005']: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/linkedin.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials['Material.001']}
      position={[-13.63, 0.37, -2.55]}
      scale={[2.98, 0.75, 3.02]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.materials['Material.005']}
      position={[-14.88, 0.37, -2.35]}
      scale={[1, 0.85, 1.4]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube002.geometry}
      material={gltf.materials['Material.002']}
      position={[-13.56, 0.44, -2.37]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder.geometry}
      material={gltf.materials['Material.005']}
      position={[-14.92, 0.37, -3.99]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[-0.36, -0.85, -0.29]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
